service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Resource: "arn:aws:dynamodb:*:*:*"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

functions:
  listImages:
    handler: image.index
    events:
      - http:
          method: get
          path: images
  addImage:
    handler: image.create
    events:
      - http:
          method: post
          path: images
  deleteImage:
    handler: image.remove
    events:
      - http:
          method: delete
          path: images

custom:
  dynamodb:
    start:
      migrate: true
  serverless-offline:
    port: 8080

resources:
  Resources:
    Image:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Image
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

