service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Resource: "arn:aws:dynamodb:*:*:*"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

functions:
  listImages:
    handler: image.index
    events:
      - http:
          method: get
          path: images
  addImage:
    handler: image.create
    events:
      - http:
          method: post
          path: images
  deleteImage:
    handler: image.remove
    events:
      - http:
          method: delete
          path: images
  # Example without LAMBDA-PROXY integration
  # Invoking locally:
  # sls webpack invoke -f first
  first:
    handler: first.hello
  # Example with LAMBDA-PROXY integration
  # Invoking locally:
  # sls webpack invoke -f second
  second:
    handler: second.hello
    events:
      - http:
          method: get
          path: second
